import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import { MantineProvider } from "@mantine/core";
import { Toaster } from "sonner";

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${lato.className} antialiased`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
